### ISSUE TITLE
pbit-tools export-bim not return error response for a thin report (no embedded model)

### ISSUE THREAD

**Issue by BVMather** [action-bi-toolkit/pbi-tools#33]
When invoking pbi-tools export-bim for a thin report (no embedded model) then the $LASTEXITCODE returned = 0 and the final line of the response is "A BIM file could not be exported."

Should this be returned as an error?

**Comment by ViacheslavKokhno** [comment]
Hi! I have the same error. Did you fix this bug? Maybe you have detailed instructions for this action.

**Comment by mthierba** [comment]
> Hi! I have the same error. Did you fix this bug? Maybe you have detailed instructions for this action.

Yes, that was fixed in beta.6, released on 11 Oct 21.
